name = "glisp"
version = "1.0.1"

description = "A simple Lisp interpreter implemented in Gleam. Features a REPL, basic Lisp functionality including arithmetic operations, list manipulation, conditionals, and variable definitions."
licences = ["Apache-2.0"]
repository = { type = "github", user = "APConduct", repo = "glisp" }

[dependencies]
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
input = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
